### ISSUE TITLE
support non-github plugins

### ISSUE THREAD

**Issue by teto** [nvim-neorocks/nurr#32]
I wanted to add https://git.sr.ht/~whynothugo/lsp_lines.nvim to nurr but so far it showcases only github plugins.
I think I found only one case where we could not use a full url instead of the github handles `USER/REPO` in:
   .github/workflows/publish.yml
 ```
      - name: Checkout plugin repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.plugin.name }}
          path: .
          fetch-depth: 0
```
https://github.com/actions/checkout

seems like repository could accept the sr.ht url too. Gonna try
